// SceneScript Mat3/Mat4 values shared by value and callback modules.
static const char* WE_MATRIX_PRELUDE =
    "// Column-major matrices. Arithmetic returns new values; translation(position)\n"
    "// and direct .m edits are the explicit mutating operations.\n"
    "if (!globalThis.Mat4) {\n"
    "    const {Vec2,Vec3,Vec4} = globalThis;\n"
    "    const radians = Math.PI / 180, degrees = 180 / Math.PI;\n"
    "    function determinant(m, n) {\n"
    "        if (n === 1) return m[0];\n"
    "        let result = 0;\n"
    "        for (let column = 0; column < n; column++) {\n"
    "            result += (column % 2 ? -1 : 1) * m[column*n] * determinant(minor(m,n,0,column),n-1);\n"
    "        }\n"
    "        return result;\n"
    "    }\n"
    "    function minor(m,n,row,column) {\n"
    "        const result = [];\n"
    "        for (let c = 0; c < n; c++) if (c !== column)\n"
    "            for (let r = 0; r < n; r++) if (r !== row) result.push(m[c*n+r]);\n"
    "        return result;\n"
    "    }\n"
    "    function makeMatrix(n) {\n"
    "        const axes = ['x','y','z','w'];\n"
    "        const Vector = n === 4 ? Vec4 : Vec3, Point = n === 4 ? Vec3 : Vec2;\n"
    "        function Matrix() { this.m = Array.from({length:n*n},(_,i) => i%(n+1) === 0 ? 1 : 0); }\n"
    "        Object.defineProperty(Matrix,'name',{value:'Mat'+n});\n"
    "        function matrix(m) { const result = new Matrix(); result.m = m; return result; }\n"
    "        Matrix.identity = () => new Matrix();\n"
    "        Matrix.fromTranslation = function(v) { const result = new Matrix(); result.translation(v); return result; };\n"
    "        Matrix.fromScale = function(v) {\n"
    "            const result = new Matrix();\n"
    "            for (let i=0;i<n-1;i++) result.m[i*(n+1)] = typeof v === 'number' ? v : v[axes[i]];\n"
    "            return result;\n"
    "        };\n"
    "        const p = Matrix.prototype;\n"
    "        p.translation = function(v) {\n"
    "            if (v === undefined) return new Point(...this.m.slice(n*(n-1),n*n-1));\n"
    "            for (let i=0;i<n-1;i++) this.m[n*(n-1)+i] = v[axes[i]] ?? 0;\n"
    "        };\n"
    "        p.copy = function() { return matrix(this.m.slice()); };\n"
    "        p.add = function(other) { return matrix(this.m.map((v,i)=>v+other.m[i])); };\n"
    "        p.subtract = function(other) { return matrix(this.m.map((v,i)=>v-other.m[i])); };\n"
    "        p.multiply = function(other) {\n"
    "            if (typeof other === 'number') return matrix(this.m.map(v=>v*other));\n"
    "            if (!other.m) {\n"
    "                const result = new Vector();\n"
    "                for (let r=0;r<n;r++) {\n"
    "                    result[axes[r]]=0;\n"
    "                    for (let k=0;k<n;k++) result[axes[r]]+=this.m[k*n+r]*other[axes[k]];\n"
    "                }\n"
    "                return result;\n"
    "            }\n"
    "            const result = Array(n*n).fill(0);\n"
    "            for (let c=0;c<n;c++) for (let r=0;r<n;r++) for (let k=0;k<n;k++)\n"
    "                result[c*n+r]+=this.m[k*n+r]*other.m[c*n+k];\n"
    "            return matrix(result);\n"
    "        };\n"
    "        p.translate = function(v) { return this.multiply(Matrix.fromTranslation(v)); };\n"
    "        p.scale = function(v) { return this.multiply(Matrix.fromScale(v)); };\n"
    "        p.rotate = function(angle,axis) { return this.multiply(Matrix.fromRotation(angle,axis)); };\n"
    "        function transform(m,v,w) {\n"
    "            const result = new Point();\n"
    "            for (let r=0;r<n-1;r++) {\n"
    "                result[axes[r]]=m[n*(n-1)+r]*w;\n"
    "                for (let k=0;k<n-1;k++) result[axes[r]]+=m[k*n+r]*(v[axes[k]] ?? 0);\n"
    "            }\n"
    "            return result;\n"
    "        }\n"
    "        p.transformPoint = function(v) { return transform(this.m,v,1); };\n"
    "        p.transformDirection = function(v) { return transform(this.m,v,0); };\n"
    "        p.transpose = function() { return matrix(this.m.map((_,i)=>this.m[(i%n)*n+Math.floor(i/n)])); };\n"
    "        p.determinant = function() { return determinant(this.m,n); };\n"
    "        p.inverse = function() {\n"
    "            const det=this.determinant();\n"
    "            if (!Number.isFinite(det) || det === 0) throw new RangeError('Cannot invert singular matrix');\n"
    "            return matrix(this.m.map((_,i)=>{\n"
    "                const row=Math.floor(i/n), column=i%n;\n"
    "                return ((row+column)%2 ? -1 : 1)*determinant(minor(this.m,n,row,column),n-1)/det;\n"
    "            }));\n"
    "        };\n"
    "        p.equals = function(other) { return !!other?.m && other.m.length === n*n && this.m.every((v,i)=>Math.abs(v-other.m[i])<=1e-6); };\n"
    "        p.toString = function() { return this.m.join(' '); };\n"
    "        return Matrix;\n"
    "    }\n"
    "    const Mat4 = makeMatrix(4), Mat3 = makeMatrix(3);\n"
    "    Mat4.fromBasis = function(right,up,forward) {\n"
    "        const result = new Mat4();\n"
    "        [right,up,forward].forEach((v,i)=>{ result.m[i*4]=v.x; result.m[i*4+1]=v.y; result.m[i*4+2]=v.z; });\n"
    "        return result;\n"
    "    };\n"
    "    Mat4.fromRotation = function(angle,axis) {\n"
    "        const length=Math.hypot(axis.x,axis.y,axis.z);\n"
    "        if (!length) return new Mat4();\n"
    "        const x=axis.x/length,y=axis.y/length,z=axis.z/length,c=Math.cos(angle*radians),s=Math.sin(angle*radians),t=1-c;\n"
    "        return Mat4.fromBasis(new Vec3(t*x*x+c,t*x*y+s*z,t*x*z-s*y),\n"
    "            new Vec3(t*x*y-s*z,t*y*y+c,t*y*z+s*x),new Vec3(t*x*z+s*y,t*y*z-s*x,t*z*z+c));\n"
    "    };\n"
    "    Mat4.fromEuler = function(x,y,z) {\n"
    "        if (typeof x === 'object') { z=x.z; y=x.y; x=x.x; }\n"
    "        return Mat4.fromRotation(z ?? 0,new Vec3(0,0,1)).multiply(Mat4.fromRotation(y ?? 0,new Vec3(0,1,0)))\n"
    "            .multiply(Mat4.fromRotation(x ?? 0,new Vec3(1,0,0)));\n"
    "    };\n"
    "    Mat4.compose = (translation,rotation,scale) => Mat4.fromTranslation(translation).multiply(Mat4.fromEuler(rotation)).scale(scale);\n"
    "    Mat4.lookAt = function(eye,center,up) {\n"
    "        const forward=eye.subtract(center).normalize(),right=up.cross(forward).normalize(),vertical=forward.cross(right);\n"
    "        const result=Mat4.fromBasis(right,vertical,forward).transpose();\n"
    "        result.translation(new Vec3(-right.dot(eye),-vertical.dot(eye),-forward.dot(eye)));\n"
    "        return result;\n"
    "    };\n"
    "    Mat4.prototype.right = function() { return new Vec3(this.m[0],this.m[1],this.m[2]); };\n"
    "    Mat4.prototype.up = function() { return new Vec3(this.m[4],this.m[5],this.m[6]); };\n"
    "    Mat4.prototype.forward = function() { return new Vec3(this.m[8],this.m[9],this.m[10]); };\n"
    "    Mat4.prototype.normalMatrix = function() { return Mat3.fromMat4(this).inverse().transpose(); };\n"
    "    Mat4.prototype.decompose = function() {\n"
    "        let right=this.right(),up=this.up(),forward=this.forward();\n"
    "        const scale=new Vec3(right.length(),up.length(),forward.length());\n"
    "        if (right.cross(up).dot(forward)<0) scale.x=-scale.x;\n"
    "        right=scale.x ? right.divide(scale.x) : new Vec3(1,0,0);\n"
    "        up=scale.y ? up.divide(scale.y) : new Vec3(0,1,0);\n"
    "        forward=scale.z ? forward.divide(scale.z) : new Vec3(0,0,1);\n"
    "        const y=Math.asin(Math.max(-1,Math.min(1,-right.z)));\n"
    "        const regular=Math.abs(Math.cos(y))>1e-7;\n"
    "        const x=regular ? Math.atan2(up.z,forward.z) : Math.atan2(-forward.y,up.y);\n"
    "        const z=regular ? Math.atan2(right.y,right.x) : 0;\n"
    "        return {translation:this.translation(),rotation:new Vec3(x*degrees,y*degrees,z*degrees),scale};\n"
    "    };\n"
    "    Mat4.prototype.extractEuler = function() { return this.decompose().rotation; };\n"
    "    Mat3.fromBasis = function(right,up) {\n"
    "        const result=new Mat3(); result.m[0]=right.x; result.m[1]=right.y; result.m[3]=up.x; result.m[4]=up.y; return result;\n"
    "    };\n"
    "    Mat3.fromRotation = function(angle) {\n"
    "        const c=Math.cos(angle*radians),s=Math.sin(angle*radians); return Mat3.fromBasis(new Vec2(c,s),new Vec2(-s,c));\n"
    "    };\n"
    "    Mat3.fromMat4 = function(source) {\n"
    "        const result=new Mat3(); result.m=source.m.filter((_,i)=>i<12 && i%4<3); return result;\n"
    "    };\n"
    "    Mat3.compose = (translation,rotation,scale) => Mat3.fromTranslation(translation).rotate(rotation).scale(scale);\n"
    "    Mat3.prototype.angle = function() { return Math.atan2(this.m[1],this.m[0])*degrees; };\n"
    "    Mat3.prototype.decompose = function() {\n"
    "        const m=this.m,scale=new Vec2(Math.hypot(m[0],m[1]),Math.hypot(m[3],m[4]));\n"
    "        if (m[0]*m[4]-m[1]*m[3]<0) scale.x=-scale.x;\n"
    "        return {translation:this.translation(),rotation:Math.atan2(m[1]/(scale.x || 1),m[0]/(scale.x || 1))*degrees,scale};\n"
    "    };\n"
    "    globalThis.Mat4=Mat4; globalThis.Mat3=Mat3;\n"
    "}\n"
;
