// SceneScript media event classes and per-module change delivery.
static const char* WE_MEDIA_PRELUDE =
    "// Event objects are fresh for each callback, including their mutable Vec3 colors.\n"
    "if (!globalThis.__weDispatchMedia) {\n"
    "    globalThis.MediaStatusEvent = class MediaStatusEvent { constructor(value) { Object.assign(this, value); } };\n"
    "    globalThis.MediaPlaybackEvent = class MediaPlaybackEvent { constructor(value) { Object.assign(this, value); } };\n"
    "    Object.defineProperties(MediaPlaybackEvent, {\n"
    "        PLAYBACK_STOPPED: {value: 0}, PLAYBACK_PLAYING: {value: 1}, PLAYBACK_PAUSED: {value: 2}\n"
    "    });\n"
    "    globalThis.MediaPropertiesEvent = class MediaPropertiesEvent { constructor(value) { Object.assign(this, value); } };\n"
    "    globalThis.MediaTimelineEvent = class MediaTimelineEvent { constructor(value) { Object.assign(this, value); } };\n"
    "    globalThis.MediaThumbnailEvent = class MediaThumbnailEvent {\n"
    "        constructor(value) {\n"
    "            Object.assign(this, value);\n"
    "            for (const name of ['primaryColor', 'secondaryColor', 'tertiaryColor', 'textColor', 'highContrastColor'])\n"
    "                this[name] = new Vec3(value[name]);\n"
    "        }\n"
    "    };\n"
    "    const events = [\n"
    "        ['mediaStatusChanged', MediaStatusEvent], ['mediaPlaybackChanged', MediaPlaybackEvent],\n"
    "        ['mediaPropertiesChanged', MediaPropertiesEvent], ['mediaThumbnailChanged', MediaThumbnailEvent],\n"
    "        ['mediaTimelineChanged', MediaTimelineEvent]\n"
    "    ];\n"
    "    globalThis.__weDispatchMedia = function(state, callbacks, snapshot) {\n"
    "        if (!snapshot) return;\n"
    "        const previous = state.mediaEvents || (state.mediaEvents = Object.create(null));\n"
    "        for (const [name, Event] of events) {\n"
    "            if (typeof callbacks[name] !== 'function' || !snapshot[name]) continue;\n"
    "            const value = JSON.stringify(snapshot[name]);\n"
    "            const identity = name === 'mediaThumbnailChanged' ? JSON.stringify([value, snapshot.thumbnailIdentifier]) : value;\n"
    "            if (previous[name] === identity) continue;\n"
    "            // Remember delivery before calling authored code. A failing listener\n"
    "            // must not permanently prevent the other events or later updates.\n"
    "            previous[name] = identity;\n"
    "            callbacks[name](new Event(JSON.parse(value)));\n"
    "        }\n"
    "    };\n"
    "}\n"
    ;
