// Shared asset handles for value and callback modules.
static const char* WE_ASSET_PRELUDE =
    "// Asset handles are scene-owned opaque references. Font properties resolve\n"
    "// their paths before the native JSON exchange, including cross-script handles.\n"
    "if (!globalThis.__weRegisterAsset) {\n"
    "    const paths = new WeakMap(), handles = new Map();\n"
    "    globalThis.__weAssetPath = function(value) { return paths.get(value); };\n"
    "    globalThis.__weRegisterAsset = function(file, precache = false) {\n"
    "        if (typeof file !== 'string' || !file || file.includes('\\0'))\n"
    "            throw new TypeError('Asset path must be a nonempty relative string');\n"
    "        let path = file.replace(/\\\\/g, '/');\n"
    "        const components = path.split('/');\n"
    "        if (path.startsWith('/') || path.includes(':') || components.includes('..'))\n"
    "            throw new RangeError('Asset path must stay within the wallpaper assets');\n"
    "        path = components.filter(part => part && part !== '.').join('/');\n"
    "        if (!path) throw new TypeError('Asset path must name a file');\n"
    "        // Registration identifies packaged assets; loading is performed by\n"
    "        // the consuming renderer. Material precaching needs a dynamic loader.\n"
    "        if (handles.has(path)) return handles.get(path);\n"
    "        const handle = Object.create(null);\n"
    "        Object.defineProperties(handle, {\n"
    "            toJSON: {value() { return path; }},\n"
    "            [Symbol.toPrimitive]: {value() { return path; }}\n"
    "        });\n"
    "        Object.freeze(handle);\n"
    "        paths.set(handle, path); handles.set(path, handle);\n"
    "        return handle;\n"
    "    };\n"
    "}\n";
