// SceneScript vector values share arithmetic across their dimensions.
// Included in both value and callback module initialization.
// Constructors and basic arithmetic avoid per-component JS callbacks.
static const char* WE_VECTOR_PRELUDE =
    "  if (!globalThis.Vec4) {\n"
    "    function makeVectorClass(size) {\n"
    "      const components = ['x', 'y', 'z', 'w'].slice(0, size);\n"
    "      function Vector(value, y, z, w) {\n"
    "        if (typeof value === 'string') {\n"
    "          const parts = value.trim().split(/\\s+/).map(Number);\n"
    "          this.x = parts[0] ?? 0; this.y = parts[1] ?? 0;\n"
    "          if (size > 2) this.z = parts[2] ?? 0;\n"
    "          if (size > 3) this.w = parts[3] ?? 0;\n"
    "        } else if (value !== null && typeof value === 'object') {\n"
    "          this.x = value.x ?? 0; this.y = value.y ?? 0;\n"
    "          if (size > 2) this.z = value.z ?? 0;\n"
    "          if (size > 3) this.w = value.w ?? 0;\n"
    "        } else {\n"
    "          this.x = value ?? 0;\n"
    "          this.y = arguments.length === 1 ? this.x : (y ?? 0);\n"
    "          if (size > 2) this.z = arguments.length === 1 ? this.x : (z ?? 0);\n"
    "          if (size > 3) this.w = arguments.length === 1 ? this.x : (w ?? 0);\n"
    "        }\n"
    "      }\n"
    "      Object.defineProperty(Vector, 'name', {value: 'Vec' + size});\n"
    "      function component(value, key) { return typeof value === 'number' ? value : (value[key] === undefined ? 0 : value[key]); }\n"
    "      function mapped(value, operation) {\n"
    "        const result = new Vector();\n"
    "        components.forEach(key => result[key] = operation(value[key], key));\n"
    "        return result;\n"
    "      }\n"
    "      const p = Vector.prototype;\n"
    "      p.copy = function() { return new Vector(this); };\n"
    "      p.add = function(value) {\n"
    "        const scalar = typeof value === 'number';\n"
    "        const result = new Vector();\n"
    "        result.x = this.x + (scalar ? value : (value.x ?? 0));\n"
    "        result.y = this.y + (scalar ? value : (value.y ?? 0));\n"
    "        if (size > 2) result.z = this.z + (scalar ? value : (value.z ?? 0));\n"
    "        if (size > 3) result.w = this.w + (scalar ? value : (value.w ?? 0));\n"
    "        return result;\n"
    "      };\n"
    "      p.subtract = function(value) {\n"
    "        const scalar = typeof value === 'number';\n"
    "        const result = new Vector();\n"
    "        result.x = this.x - (scalar ? value : (value.x ?? 0));\n"
    "        result.y = this.y - (scalar ? value : (value.y ?? 0));\n"
    "        if (size > 2) result.z = this.z - (scalar ? value : (value.z ?? 0));\n"
    "        if (size > 3) result.w = this.w - (scalar ? value : (value.w ?? 0));\n"
    "        return result;\n"
    "      };\n"
    "      p.multiply = function(value) {\n"
    "        const scalar = typeof value === 'number';\n"
    "        const result = new Vector();\n"
    "        result.x = this.x * (scalar ? value : (value.x ?? 0));\n"
    "        result.y = this.y * (scalar ? value : (value.y ?? 0));\n"
    "        if (size > 2) result.z = this.z * (scalar ? value : (value.z ?? 0));\n"
    "        if (size > 3) result.w = this.w * (scalar ? value : (value.w ?? 0));\n"
    "        return result;\n"
    "      };\n"
    "      p.divide = function(value) {\n"
    "        const scalar = typeof value === 'number';\n"
    "        const result = new Vector();\n"
    "        result.x = this.x / (scalar ? value : (value.x ?? 0));\n"
    "        result.y = this.y / (scalar ? value : (value.y ?? 0));\n"
    "        if (size > 2) result.z = this.z / (scalar ? value : (value.z ?? 0));\n"
    "        if (size > 3) result.w = this.w / (scalar ? value : (value.w ?? 0));\n"
    "        return result;\n"
    "      };\n"
    "      p.scale = p.multiply;\n"
    "      p.dot = function(value) { return components.reduce((sum, key) => sum + this[key] * component(value, key), 0); };\n"
    "      p.lengthSqr = function() { return this.dot(this); };\n"
    "      p.length = function() { return Math.sqrt(this.lengthSqr()); };\n"
    "      p.distanceSqr = function(value) { return this.subtract(value).lengthSqr(); };\n"
    "      p.distance = function(value) { return Math.sqrt(this.distanceSqr(value)); };\n"
    "      p.normalize = function() { const length = this.length(); return length > 0 ? this.divide(length) : new Vector(); };\n"
    "      p.equals = function(value) { return components.every(key => Math.abs(this[key] - component(value, key)) <= 0.000001); };\n"
    "      p.isFinite = function() { return components.every(key => Number.isFinite(this[key])); };\n"
    "      p.negate = function() { return this.multiply(-1); };\n"
    "      p.reflect = function(normal) { return this.subtract(normal.multiply(2 * this.dot(normal))); };\n"
    "      p.project = function(value) { const length = value.lengthSqr(); return length > 0 ? value.multiply(this.dot(value) / length) : new Vector(); };\n"
    "      p.mix = function(value, amount) { return mapped(this, (x, key) => x + (component(value, key) - x) * component(amount, key)); };\n"
    "      p.min = function(value) { return mapped(this, (x, key) => Math.min(x, component(value, key))); };\n"
    "      p.max = function(value) { return mapped(this, (x, key) => Math.max(x, component(value, key))); };\n"
    "      p.clamp = function(low, high) { return this.max(low).min(high); };\n"
    "      p.abs = function() { return mapped(this, Math.abs); };\n"
    "      p.sign = function() { return mapped(this, Math.sign); };\n"
    "      p.round = function() { return mapped(this, Math.round); };\n"
    "      p.floor = function() { return mapped(this, Math.floor); };\n"
    "      p.ceil = function() { return mapped(this, Math.ceil); };\n"
    "      p.fract = function() { return mapped(this, x => x - Math.floor(x)); };\n"
    "      p.mod = function(value) { return mapped(this, (x, key) => { const y = component(value, key); return x - y * Math.floor(x / y); }); };\n"
    "      p.step = function(edge) { return mapped(this, (x, key) => x < component(edge, key) ? 0 : 1); };\n"
    "      p.smoothStep = function(low, high) { const t = this.subtract(low).divide(new Vector(high).subtract(low)).clamp(0, 1); return t.multiply(t).multiply(t.multiply(-2).add(3)); };\n"
    "      p.toString = function() { return components.map(key => String(this[key])).join(' '); };\n"
    "      return Vector;\n"
    "    }\n"
    "    globalThis.Vec2 = makeVectorClass(2);\n"
    "    globalThis.Vec3 = makeVectorClass(3);\n"
    "    globalThis.Vec4 = makeVectorClass(4);\n"
    "    globalThis.Vec2.prototype.perpendicular = function() { return new globalThis.Vec2(-this.y, this.x); };\n"
    "    globalThis.Vec3.prototype.cross = function(v) { return new globalThis.Vec3(this.y * v.z - this.z * v.y, this.z * v.x - this.x * v.z, this.x * v.y - this.y * v.x); };\n"
    "    globalThis.Vec3.prototype.refract = function(normal, eta) { const dot = this.dot(normal), k = 1 - eta * eta * (1 - dot * dot); return k < 0 ? new globalThis.Vec3() : this.multiply(eta).subtract(normal.multiply(eta * dot + Math.sqrt(k))); };\n"
    "    globalThis.Vec3.prototype.angleBetween = function(value) { const length = this.length() * value.length(); return length > 0 ? Math.acos(Math.max(-1, Math.min(1, this.dot(value) / length))) * 180 / Math.PI : 0; };\n"
    "    globalThis.Vec3.fromSpherical = function(radius, theta, phi) { theta *= Math.PI / 180; phi *= Math.PI / 180; return new globalThis.Vec3(radius * Math.sin(theta) * Math.cos(phi), radius * Math.cos(theta), radius * Math.sin(theta) * Math.sin(phi)); };\n"
    "    globalThis.Vec3.prototype.toSpherical = function() { const radius = this.length(); return radius > 0 ? new globalThis.Vec3(radius, Math.acos(Math.max(-1, Math.min(1, this.y / radius))) * 180 / Math.PI, Math.atan2(this.z, this.x) * 180 / Math.PI) : new globalThis.Vec3(); };\n"
    "  }\n"
    ;
